---
- name: Install Python Docker
  hosts: all
  tags:
    - install

  tasks:
    - name: Install Pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install Docker
      pip:
        name:
          - docker
          - docker-compose

# - hosts: all
#   roles:
#     - geerlingguy.docker
#   tags:
#     - install

- name: Deploy Composes
  hosts: all
  tags:
    - apps
  vars:
    composes_dir: /apps
    composes:
      - repo: https://github.com/ondrejsika/docker-compose-app--example
        name: demo-app
        rev: master
        compose_chain: docker-compose.yml
      - repo: https://github.com/ondrejsika/docker-compose-app--example
        name: demo-app-2
        rev: new-branch
        dotenv_content: |
          PORT=8080
        compose_chain: docker-compose.yml
      - repo: https://github.com/ondrejsika/docker-compose-app--example
        name: demo-app-3
        rev: hello-branch
        compose_chain: docker-compose.yml
        dotenv_content: |
          PORT=8081
  roles:
    - compose
