---
- name: Update Git Repos
  git:
    repo: "{{ item.repo }}"
    dest: "{{ composes_dir }}/{{item.name}}"
    version: "{{ item.rev }}"
  with_items: "{{ composes }}"

- name: Ensure docker-compose up
  docker_compose:
    project_src: "{{ composes_dir }}/{{ item.name }}"
    # file: "{{item.compose_chain}}"
  with_items: "{{ composes }}"
